<?
$PERM["video"]["*"]="R";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["forum"]["8"]="X";
$PERM["forum"]["6"]="X";
$PERM["forum"]["*"]="D";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>