<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Заказы");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:sale.personal.order", 
	".default", 
	array(
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/personal/order/",
		"ORDERS_PER_PAGE" => "10",
		"PATH_TO_PAYMENT" => "/personal/order/payment/",
		"PATH_TO_BASKET" => "/personal/cart/",
		"SET_TITLE" => "Y",
		"SAVE_IN_SESSION" => "N",
		"NAV_TEMPLATE" => "arrows",
		"SHOW_ACCOUNT_NUMBER" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"DETAIL_HIDE_USER_INFO" => array(
			0 => "0",
		),
		"PROP_1" => array(
			0 => "28",
			1 => "29",
			2 => "30",
		),
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_GROUPS" => "Y",
		"PATH_TO_CATALOG" => "/catalog/",
		"CUSTOM_SELECT_PROPS" => array(
		),
		"HISTORIC_STATUSES" => array(
			0 => "AC",
			1 => "C",
			2 => "DE",
			3 => "F",
		),
		"RESTRICT_CHANGE_PAYSYSTEM" => array(
			0 => "AC",
			1 => "C",
			2 => "DE",
			3 => "DS",
			4 => "F",
			5 => "IC",
			6 => "P",
			7 => "PR",
			8 => "RS",
			9 => "SC",
			10 => "SP",
			11 => "ZE",
			12 => "ZS",
		),
		"ORDER_DEFAULT_SORT" => "STATUS",
		"ALLOW_INNER" => "N",
		"ONLY_INNER_FULL" => "N",
		"STATUS_COLOR_AC" => "gray",
		"STATUS_COLOR_C" => "gray",
		"STATUS_COLOR_DE" => "gray",
		"STATUS_COLOR_DS" => "gray",
		"STATUS_COLOR_F" => "gray",
		"STATUS_COLOR_IC" => "gray",
		"STATUS_COLOR_IR" => "gray",
		"STATUS_COLOR_N" => "green",
		"STATUS_COLOR_P" => "yellow",
		"STATUS_COLOR_PR" => "gray",
		"STATUS_COLOR_RS" => "gray",
		"STATUS_COLOR_SC" => "gray",
		"STATUS_COLOR_SP" => "gray",
		"STATUS_COLOR_WC" => "gray",
		"STATUS_COLOR_WP" => "gray",
		"STATUS_COLOR_Z" => "gray",
		"STATUS_COLOR_ZE" => "gray",
		"STATUS_COLOR_ZS" => "gray",
		"STATUS_COLOR_PSEUDO_CANCELLED" => "red",
		"SEF_URL_TEMPLATES" => array(
			"list" => "index.php",
			"detail" => "detail/#ID#/",
			"cancel" => "cancel/#ID#/",
		)
	),
	false
);?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php");?>